### PR TITLE
I23 hotfix for demo

### LINKED ISSUE #23: Hotfix for the demo
- [x] update port number in api to 8991
- [x] close node-server on SIGTERM and SIGINT
- [x] check if message was sent in DM in the onMessage function
- [x] wrap kickUser in a try-catch so it won't crash the program when a user is not a member of a group
- [x] in the manageGroups function check whether the user is already a member of the group he just unlocked

### PR DESCRIPTION
**Pull request by schronck**
Closes #23

### CODE REVIEW

File: src/api/actions.ts [hunk 1]
```diff
@@ -10,30 +11,56 @@ const generateInvite = async (groupId: string): Promise<string> =>
...
 
   if (isUpgrade) {
-    const message: string =
-      "Oh hello! I'm more than happy to tell you that you can join these " +
-      `groups below:\n${invites.join("\n")}`;
+    const isMember = async (groupId: string): Promise<Boolean> => {
+      try {
+        const member = await Bot.Client.getChatMember(
+          groupId,
+          Number(platformUserId)
```
Comment (dezsim) [inline src/api/actions.ts:25]: Use unary operator here, and if there are any `Number()` cast, we should refactor it for consistency.
